RWC2019: Add Options message and LabeledImage
tue-robotics/telegram_ros pull request #13
Opened 2019-07-12 10:46 UTC by LoyVanBeek

- LabeledImage allows to explicitly pair an image and a label. `master` currently optionally pairs these two via the Image's frame_id but that feels a bit like a hack. 
- Options allows to ask a question and then suggest a reply via a custom keyboard in Telegram.

2019-07-12 10:50 UTC, MatthijsBurgh requested changes
Please fix the EOFs, and separate msg package would be better

2019-07-12 10:50 UTC, MatthijsBurgh commented on CMakeLists.txt
> +)
Fix EOF

2019-07-12 10:50 UTC, MatthijsBurgh commented on msg/Options.msg
> +string[] options
Fix EOF

2019-07-12 11:32 UTC, LoyVanBeek commented
Maybe the messages would alsually better fit in the HMI msgs?

2019-07-12 11:47 UTC, ar13pit commented
> Maybe the messages would alsually better fit in the HMI msgs?

Only if other clients are using it. Else it wouldn't make sense to generalize it yet.

2019-09-10 18:13 UTC, JosjaG commented on CMakeLists.txt
> +)
fixed

2019-09-10 18:13 UTC, JosjaG commented on msg/Options.msg
> +string[] options
fixed

2019-09-10 18:20 UTC, MatthijsBurgh approved these changes

2019-09-10 18:21 UTC, MatthijsBurgh commented
@JosjaG you can merge this if CI succeedes and you agree with my last commit

2019-09-17 18:01 UTC, merged